### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by luchfiummi** [luislutz/Arduino_Quantizer#2]
excellent work.  Love it.  But I did notice a little mistake.  When I select the switch sw2 so that it does not work with external signals if there is something externally connected such as an lfo or an offset, I notice a change in the scale that is at that moment.  That is, there should be no changes if the sw switch is selecting the quantizer to work internally.. Thanks

**Comment by luislutz** [comment]
Hey! Thanks for your hint! But i dont really know exactly what you mean. Could you give any more detail what happens on your build? Then i could take a look at it and maybe post a fix :)

**Comment by luchfiummi** [comment]
Thanks!.  It was a construction problem on mine.  Excellent this quantizer
